version: "2"
services:
  app:
    build: .
    volumes:
      - ./data/:/app/data/
    environment:
      TGBOT_TOKEN: ${TGBOT_TOKEN}
      TG_CHAT_ID: ${TG_CHAT_ID}
      GITLAB_ATOM_LINK: ${GITLAB_ATOM_LINK}
    restart: always
